### ISSUE TITLE
Support mercurial packages

### ISSUE THREAD

**Issue by adrienkohlbecker** [joewalnes/go-getter#1]
Hello,

Thanks for this helpful little tool :smile:
It does not work for packages hosted by golang.org though:

```
> go-getter Gofile
golang.org/x/text (583b6acb6c7c552566973feda06f839192ccd02e)
remote: 404 page not found
fatal: repository 'https://golang.org/x/text.git/' not found
```

I tried setting the repo to the github mirror (at github.com/golang/text ) but the code needs to be imported via golang:

```
util/normalize.go:8:2: code in directory ~/.gopath/src/github.com/golang/text/transform expects import "golang.org/x/text/transform"
```

Cheers,

**Comment by joewalnes** [comment]
Thanks for report. Looking closer it seems it's because golang.org/x/ uses mercurial and not git. Renamed issue.

**Comment by joewalnes** [comment]
Should be possible to adapt the script to try git and if that fails try hg.

Small task, but I've posted a small $20 bounty if anyone wants to take a crack at it.
https://www.bountysource.com/issues/11698279-support-mercurial-packages

**Comment by adrienkohlbecker** [comment]
Hey so I looked at it a bit more and apparently it's still git, but there is a url rewrite going on:
This meta tag is in the source for https://golang.org/x/text:
`<meta name="go-import" content="golang.org/x/text git https://go.googlesource.com/text">`

**Comment by sriniprash** [comment]
I am able to fetch golang.org/x/text by using the "git" protocol instead of https i.e
`git clone git://golang.org/x/text.git`. This works for all github.com and golang.org repos. Regarding support for mercurial will it make sense to add a 3rd field in the GoFile i.e the VCS used? Any comments?

**Comment by joewalnes** [comment]
@sriniprash Ahh right. I tried using the ssh protocol, but didn't occur to me to try git://.

Yes, I think it makes sense to add a column with which vcs + transport to use

**Comment by sriniprash** [comment]
@joewalnes Created a PR for the same. Please review it and share your comments.

**Comment by stuart-warren** [comment]
why not leave `go get` to do its thing, use it's inbuilt logic to clone all the repos, then have go-getter to go into each local copy and checkout the correct revision where it's easy to work out the vcs.

**Comment by joewalnes** [comment]
@sriniprash: Awesome, checking it out now!

@stuart-warren: Interesting idea! I like it. It seems that @sriniprash has a working implementation without go get but if we run into issues we'll look at that too.

**Comment by joewalnes** [comment]
Merged - thanks! @sriniprash go claim your bounty: https://www.bountysource.com/issues/11698279-support-mercurial-packages

As I look back at the original issue I see that it doesn't solve @adrienkohlbecker's issue - I got the wrong end of the stick on what the original issue is, so I'm going to open the `<meta name="go-import">` thing as new issue.
