### ISSUE TITLE
<meta name="go-import"> support

### ISSUE THREAD

**Issue by joewalnes** [joewalnes/go-getter#4]
(Originally reported by @adrienkohlbecker in #1).

go-getter should be able to resolve `<meta name="go-import">` as described in https://golang.org/cmd/go/.

For examples, including package `golang.org/x/text` should result in an http request to https://golang.org/x/text, which contains location of the real repository as `<meta name="go-import" content="golang.org/x/text git https://go.googlesource.com/text">`.

I'm beginning to like @stuart-warren's suggestion of using the real `go get` command for the initial checkout, which will resolve the meta tag as well as try all the supported VCSs and transports, then using regular hg/git/bzr/svn for updating to the desired revision.

**Comment by joewalnes** [comment]
$20 bounty here: https://www.bountysource.com/issues/12382001-meta-name-go-import-support

**Comment by sriniprash** [comment]
@joewalnes created a PR for the same: https://github.com/joewalnes/go-getter/pull/6

Please review it and share your comments.

**Comment by joewalnes** [comment]
LGTM
